server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
#    eureka服务器的客户端(服务消费端)如果在fetchRegistry设置为false的情况下  Feign一端启动的时候 会报错
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/